# Generated by Django 4.2.4 on 2023-09-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default='1111-11-11', verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_counts',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
